# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SocialNetwork' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SocialNetwork

  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

  target 'SocialNetworkTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SocialNetwork-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SocialNetwork-tvOS

  target 'SocialNetwork-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
